import { useState, useEffect } from "react";
import styles from "./cart.module.scss";
import Head from "next/head";
import Image from "next/image";
import CartItem from "../../component/cart_item";
import CartAfterItem from "../../component/cart_after_item";
import CartSidebar from "../../component/cart_sidebar";

const Category = () => {
  return (
    <div className={styles.cart}>
      <Head>
        <title>Nitori cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1 className={styles.h1}>カート</h1>
      </header>
      <main className={styles.main}>
        <CartItem />
        <CartAfterItem />
      </main>
      <nav className={styles.sidebar}>
        <CartSidebar />
      </nav>
    </div>
  );
};

export default Category;
